/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {StyleSheet, Text, View, TouchableOpacity} from 'react-native';
import AccessoryManager from 'react-native-accessory-manager';

export default class App extends Component {
  state = {
    status: 'starting',
    message: '--',
  };
  componentDidMount() {
    this.showPicker();
  }

  showPicker = () => {
    AccessoryManager.showPicker(
      'Testing',
      (message, nameFilter, supportedStrings) => {
        console.log(message, nameFilter, supportedStrings);
        this.setState({
          status: 'native callback received',
          message:
            JSON.stringify(message) +
            ', ' +
            nameFilter +
            ', ' +
            JSON.stringify(supportedStrings),
        });
      },
    );
  };

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆AccessoryManager example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
        <TouchableOpacity style={styles.button} onPress={this.showPicker}>
          <Text>Show picker</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
  button: {
    width: '90%',
    alignSelf: 'center',
    height: 50,
    borderRadius: 5,
    backgroundColor: 'black',
  },
});
